/* does the API log errors correctly to GA?  */

const Lws = require('../')
const lws = new Lws()
const MockResponse = require('../../mock-response')
lws.on('verbose', (key, value) => console.log(key, value))

const BrokenMock = MockBase => class extends MockBase {
  mocks () {
    return [
      {
        route: '/',
        responses: [
          { response: function (ctx) {
            throw new Error('something')
          }}
        ]
      }
    ]
  }
}
const server = lws.listen({ stack: MockResponse, mocks: BrokenMock })
